### ISSUE TITLE
Trying to run FSRT following EcoScanner vulnerability detection

### ISSUE THREAD

**Issue by sebD** [atlassian-labs/FSRT#29]
I ran this command:

```
fsrt ./my-project
```
Where my-project is the path towards the app I wish to test.

I expected this to happen:
The scanner evaluates the app and reports any issues

Instead, this happened:
The program exits with errors:

> thread 'main' panicked at crates/forge_analyzer/src/definitions.rs:359:18:
> expected class

`fsrt --version`: 
```
fsrt 0.1.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at crates/forge_analyzer/src/definitions.rs:359:18:
expected class

stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <forge_analyzer::definitions::Lowerer as swc_ecma_visit::Visit>::visit_var_declarator
   3: swc_ecma_visit::visit_decl
   4: <forge_analyzer::definitions::Lowerer as swc_ecma_visit::Visit>::visit_var_declarator
   5: swc_ecma_visit::visit_decl
   6: forge_analyzer::definitions::run_resolver
   7: fsrt::scan_directory
   8: fsrt::main
```

</p>
</details>

**Comment by jeffryan-appfire** [comment]
I'm facing the same panic error when trying to run the scanner after seeing that Atlassian announced it'd start running the scanner on deployed marketplace applications. I'm simply running it locally to get a leg up on any warnings it may give. Here's the specific error I'm seeing:
```
[repos]$ RUST_BACKTRACE=1 fsrt ./jmcf-cloud
thread 'main' panicked at crates/forge_analyzer/src/definitions.rs:411:18:
expected class
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <forge_analyzer::definitions::Lowerer as swc_ecma_visit::Visit>::visit_var_declarator
   3: swc_ecma_visit::visit_decl
   4: forge_analyzer::definitions::run_resolver
   5: fsrt::scan_directory
   6: fsrt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

BTW, I'm running on macos 13.6.1 after installing rust 1.75.0 via Homebrew. I installed FSRT via cargo as directed:
`cargo install --git https://github.com/atlassian-labs/FSRT
`
The installation showed a lot of warnings (see attached) but I didn't see any errors
[fsrt_install.txt](https://github.com/atlassian-labs/FSRT/files/13820970/fsrt_install.txt)

**Comment by jwong101** [comment]
Hi @sebD, @jeffryan-appfire,

Sorry about the late reply. Would you be able to provide a minimal reproduction of the app that causes the crash? You can also provide me with the app ID of a deployed app that FSRT's crashing on and I can take a look at it.

**Comment by jwong101** [comment]
Also, @sebD, as for your concern about the custom fields route, we've had this question come up a lot, and we definitely agree that the `ADMIN` permission is a bit too heavy handed for that API endpoint.

That being said, the main Authorization that needs to happen is to check if the user can access a custom field in the first place, since users shouldn't be able to view fields if they aren't in a project where the field exists. There unfortunately isn't a simple way to authorize the user in this case. The simplest way to check if a user can access a field is to `GET` the [fields](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-fields/#api-rest-api-3-field-get) with `asUser` and check if the supplied `field key` or `field id` is contained within the list of returned fields. There's probably other ways to do it, however, this is the simplest one we've found and have explicitly added logic to `FSRT` to allow access to custom field endpoints once this check is done. That being said, if you wish to do this check another way, let me know and I can see if I can update FSRT to also recognize your approach.

Also, if you do perform this type of check, but `FSRT` isn't recognizing it, you can reach out on the ticket if you have one and I'll close it manually, so you don't have to wait.

**Comment by MaxTheBean** [comment]
I have the same issue trying to run FSRT on Windows - inside a Docker container using the repository's [Dockerfile](https://github.com/atlassian-labs/FSRT/blob/main/Dockerfile) (modified a bit for it to work - didn't use the `FROM gcr.io/distroless/cc` base container which can't run the binaries):

Here's a more detailed stack trace while running the app built as debug instead of release.

<details><summary>Details</summary>
<p>

```
thread 'main' panicked at crates/forge_analyzer/src/definitions.rs:412:18:
expected class
stack backtrace:
   0:     0x5601021eb7dc - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5601021eb7dc - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5601021eb7dc - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5601021eb7dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560102216f3c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x560102216f3c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x5601021e794e - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x5601021eb5c4 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5601021eb5c4 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5601021ecc33 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x5601021ec954 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x5601021ed1b5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x5601021ed066 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:601:13
  13:     0x5601021ebd06 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5601021ece02 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x560101ce1975 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x560101da8efd - forge_analyzer::definitions::DefKind<F,O,I>::expect_class::h0f47e04e5b28b74e
                               at /app/crates/forge_analyzer/src/definitions.rs:412:18
  17:     0x560101da8efd - <forge_analyzer::definitions::Lowerer as swc_ecma_visit::Visit>::visit_var_declarator::h6549ca7d80f913d7
                               at /app/crates/forge_analyzer/src/definitions.rs:2852:41
  18:     0x560101db36c7 - swc_ecma_visit::visit_var_declarators::{{closure}}::hacc78e89e42c351f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  19:     0x560101db36c7 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h71237299a5665abb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/iter/macros.rs:254:21
  20:     0x560101db36c7 - swc_ecma_visit::visit_var_declarators::h07e32fa79e588e70
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  21:     0x560101db36c7 - swc_ecma_visit::Visit::visit_var_declarators::h3fc0f51b5f200cac
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  22:     0x560101db36c7 - swc_ecma_visit::visit_var_decl::h267e425848fbb8a2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  23:     0x560101db36c7 - swc_ecma_visit::Visit::visit_var_decl::hbe254143ba42ceb4
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  24:     0x560101db36c7 - swc_ecma_visit::visit_decl::h0e5c644a44e068dd
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  25:     0x560101dacbbd - swc_ecma_visit::Visit::visit_stmt::h187f991d990d811e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  26:     0x560101dacbbd - swc_ecma_visit::visit_module_item::h752b5486d72354c8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  27:     0x560101dacbbd - swc_ecma_visit::Visit::visit_module_item::h1c2675c2b8e8c056
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  28:     0x560101dacbbd - swc_ecma_visit::visit_module_items::{{closure}}::h52dd213da0163963
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  29:     0x560101dacbbd - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h5fdb14aa53c16a23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/iter/macros.rs:254:21
  30:     0x560101dacbbd - swc_ecma_visit::visit_module_items::h7a73d8b5be4e1249
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  31:     0x560101dacbbd - swc_ecma_visit::Visit::visit_module_items::h9d9d6cbfef038079
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  32:     0x560101dacbbd - swc_ecma_visit::visit_module::hda74e272d2903de5
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  33:     0x560101dacbbd - swc_ecma_visit::Visit::visit_module::h5941ea5668c106d8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  34:     0x560101dacbbd - <swc_ecma_ast::module::Module as swc_ecma_visit::VisitWith<V>>::visit_with::h42b4d4cb542c9c23                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.96.10/src/lib.rs:537:1
  35:     0x560101dacbbd - forge_analyzer::definitions::run_resolver::ha941e658d4b0fc2b
                               at /app/crates/forge_analyzer/src/definitions.rs:200:9
  36:     0x560101cee0f1 - fsrt::ForgeProject::with_files_and_sourceroot::h72fc4e94794acfef
                               at /app/crates/fsrt/src/main.rs:131:19
  37:     0x560101d04652 - fsrt::scan_directory::h6614de740ad451b8
                               at /app/crates/fsrt/src/main.rs:217:9
  38:     0x560101cffefa - fsrt::main::ha80e9f2dc21f6ef1
                               at /app/crates/fsrt/src/main.rs:448:9
  39:     0x560101ce6483 - core::ops::function::FnOnce::call_once::he71b31390560dd39
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5  40:     0x560101ce6483 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b279bee94f8cef5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:154:18
  41:     0x560101d4081d - std::rt::lang_start::{{closure}}::h97a8219a047f0ac3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:166:18
  42:     0x5601021e221b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
  43:     0x5601021e221b - std::panicking::try::do_call::h629e203a624883e4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  44:     0x5601021e221b - std::panicking::try::h7b61614724d6a4f1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  45:     0x5601021e221b - std::panic::catch_unwind::h354ac1c0268491d8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  46:     0x5601021e221b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
  47:     0x5601021e221b - std::panicking::try::do_call::h54583f67455bff32
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  48:     0x5601021e221b - std::panicking::try::hb0e12c4e01d39dc2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  49:     0x5601021e221b - std::panic::catch_unwind::h367b6339e3ca9a3b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  50:     0x5601021e221b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  51:     0x560101d0a5fc - main
  52:     0x7f39591211ca - <unknown>
  53:     0x7f3959121285 - __libc_start_main
  54:     0x560101ce2241 - _start
  55:                0x0 - <unknown>
```

</p>
</details>

**Comment by MaxTheBean** [comment]
Alright so I've investigated a bit more, as running it on the [test apps](https://github.com/atlassian-labs/FSRT/tree/main/test-apps) was working properly, so I knew I could modify our manifest / code until it works.

I found the piece of code that can make FSRT crash. It's a `typescript.ts` file with simple pseudocode inside it as follows:
```typescript
const Something = {
  someFunction() {
  }
}
export default Something;
``` 

It appears that declaring functions that way make FSRT crash. Here's a modification that now makes it work:
```typescript
const Something = {
  someFunction: function() {
  }
}
export default Something;
``` 

I hope this helps!

**Comment by jeffryan-appfire** [comment]
@jwong101 If you'd like to run against our appid here it is:
  id: ari:cloud:ecosystem::app/8b5ff96a-a06c-40e4-a906-57a8888a75dd

**Comment by jwong101** [comment]
Thanks! I'll take a look at those apps.

**Comment by jwong101** [comment]
[This commit](https://github.com/atlassian-labs/FSRT/commit/2df0fc11338389ddd9f40318c6c45388c1903545) should resolve the crash for `ari:cloud:ecosystem::app/8b5ff96a-a06c-40e4-a906-57a8888a75dd`. Let me know if it works for you @jeffryan-appfire.

**Comment by jwong101** [comment]
@MaxTheBean your issue should be fixed by [this commit](https://github.com/atlassian-labs/FSRT/commit/9e2645253a232a322312a56eb89f43dea084495e). Let me know if it works for you.

**Comment by jeffryan-appfire** [comment]
My apologies @jwong101 for not responding earlier - we were buried at the moment but your closure of the issues prompted me to look at it again. I updated my version of rust and reinstalled the scanner. It now seems to be successfully completing however it runs very, very fast - to the point that I wonder if it really did anything. I also tried the callgraph option but do not see any output. So I am not sure if I am running it properly. Another thing I noticed is that although the install works and I no longer see the error it looks like the app version hasn't changed as `fsrt --version` still reports `0.1.0`



Here's what I am seeing when I run the app.

```
[repos]$ RUST_BACKTRACE=1 fsrt ./jmcf-cloud
{"vulns":[],"scanner":"FSRT","started_at":"2024-07-01T20:12:11.679117Z","ended_at":"2024-07-01T20:12:11.679988Z","scanned":[""],"errors":false}
[repos]$ RUST_BACKTRACE=1 fsrt ./jmcf-cloud --callgraph
{"vulns":[],"scanner":"FSRT","started_at":"2024-07-01T20:15:58.469473Z","ended_at":"2024-07-01T20:15:58.470244Z","scanned":[""],"errors":false}
```

**Comment by jwong101** [comment]
Hi @jeffryan-appfire,

> My apologies @jwong101 for not responding earlier - we were buried at the moment but your closure of the issues prompted me to look at it again. 

No worries!

> I also tried the callgraph option but do not see any output. So I am not sure if I am running it properly.

Ah the `--callgraph` and `--cfg` are unimplemented at the moment. (The `--cfg` option used to
be implemented, but it was removed for reasons that I can't remember). I'll remove those flags from the `README.md` and `--help` output to reflect this.

You can check the status of the scanner by doing `FORGE_LOG=debug fsrt`. For your particular app, I checked the source, and the secret scanner and authentication scanner being quick is expected.

For the secret scanner, since your app doesn't use any [common sinks](https://github.com/atlassian-labs/FSRT/blob/main/secretdata.yaml), it shouldn't run at all.

For the authentication scanner, the webtrigger function is small, so that should run scanner.

However, for the authorization scanner, there's a current limitation of the scanner where we only identify API calls via `asApp/asUser` if we know for certain what the invoking function is. While this is resilient against shadowing, renaming, etc, the scanner currently doesn't try to resolve the function if it's dependent on a conditional. For instance[^1]:

```javascript
// assume useAsApp isn't constant and api is the default import from '@forge/api'
const func = useAsApp ? api.asApp : api.asUser;
func().requestJira(...);
```

Since FSRT doesn't know what the exact function being invoked is, it classifies it as a 'regular' function call instead of a Forge intrinsic. Ideally, we should determine the various Forge intrinsics during the actual dataflow analysis instead of when creating FSRT's intermediate representation. However, since FSRT can't at the moment, the authorization scanner ends up running pretty quickly on your app, since it can't find any Forge API call intrinsics.

We will be undertaking a project over the next couple of months to FSRT's accuracy, and I'll add this particular code pattern as something we should detect.

Let me know if you have any further questions, and I hope this explanation of FSRT's current limitation makes sense.

[^1]: The jmcf-cloud app contains a more complicated version of this pattern, but FSRT currently fails on this simple one.
