### ISSUE TITLE
FSRT crashes on a very simple app

### ISSUE THREAD

**Issue by siebenmarck** [atlassian-labs/FSRT#6]
Hi,
We've just tried to run FSRT with a couple of our more simple apps, but immediately ran into trouble where FSRT would just crash. 

```
olli@Mac % ./target/release/fsrt ../expression-tester                      
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/forge_analyzer/src/engine.rs:109:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Debugging output:
```
DEBUG dir="../expression-tester"
scan_directory dir="../expression-tester", function=None, opts=Opts { dump_cfg: false, dump_callgraph: false }
  0ms DEBUG manifest_file="../expression-tester/manifest.yml"
  load_module path="../expression-tester/src/index.js"
    visit_import_decl 
      0ms DEBUG local=(Atom('Resolver' type=dynamic), #1)
    
    0ms DEBUG variable export, ident=(Atom('handler' type=inline), #1)
    collect_functions 
      0ms DEBUG binding ident, id=(Atom('resolver' type=dynamic), #1)
      0ms DEBUG binding ident, id=(Atom('handler' type=inline), #1)
    
  
  1ms DEBUG keys=[ModId(0)]
  verify_funs 
  
  run invoked=ModItem { mod_id: ModId(0), ident: (Atom('handler' type=inline), #1) }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/forge_analyzer/src/engine.rs:109:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Used versions:
fsrt 0.1.0
cargo 1.64.0

The app's id is: `ari:cloud:ecosystem::app/a7ad5e18-c712-4333-9e38-37bf5cdbdcfd`. Any hints on what is going on here and where we went wrong are greatly appreciated.

Thank you,
 Oliver

**Comment by jwong101** [comment]
Sorry for the late response, we just went through a pretty big rewrite. I just ran the most recent version of fsrt on that app, and it seems to not crash anymore. I believe the issue was that we weren't correctly lowering resolver defined entrypoints.

**Comment by jwong101** [comment]
Closing, since the most recent version of FSRT was able to scan the current version of this app in prod.
