### ISSUE TITLE
FSRT Crashes on a prod app

### ISSUE THREAD

**Issue by ayessipovskiyDAG** [atlassian-labs/FSRT#7]
Hi @here, we've attempted to run the FSRT against our prod apps, but failed. Running FSRT for the sample apps provided works like a charm.

This is the error stack we get:
```
hread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/forge_analyzer/src/engine.rs:107:13
stack backtrace:
   0:        0x100b3437c - std::backtrace_rs::backtrace::libunwind::trace::h72c73b9e5db0005d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100b3437c - std::backtrace_rs::backtrace::trace_unsynchronized::h0241cec881bc8f92
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100b3437c - std::sys_common::backtrace::_print_fmt::h7a7ee67e414bd3d7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x100b3437c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x100b4d298 - core::fmt::write::h91497fd291c8b104
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:        0x100b31a48 - std::io::Write::write_fmt::h23fa41342cffacf4
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:        0x100b35818 - std::sys_common::backtrace::_print::h39f712a9b74dd89c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x100b35818 - std::sys_common::backtrace::print::h0be19d9a7285bd90
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x100b35818 - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:        0x100b3553c - std::panicking::default_hook::hdfe992d5fb29a991
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:        0x100b35db0 - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:        0x100b35cac - std::panicking::begin_panic_handler::{{closure}}::h06a693206403b4d5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:        0x100b347e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8998defd518dbcad
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x100b35a3c - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:        0x100b67948 - core::panicking::panic_fmt::ha46aa9af97eb193d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:        0x100b67868 - core::panicking::panic::h5713e7735cef5fa8
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:        0x10091141c - forge_analyzer::engine::Machine::run::h7a1f6acb64055427
  17:        0x1008e3b2c - fsrt::ForgeProject::verify_funs::{{closure}}::hb1e7a70c03245fd1
                               at /Users/alexandr/Projects/FSRT/crates/fsrt/src/main.rs:95:37
  18:        0x1008e3b2c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h07758b3811d2889b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:306:13
  19:        0x1008e3b2c - core::option::Option<T>::map::h3b5d6ea649a218ad
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:929:29
  20:        0x1008e3b2c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h0caefb3d874f079a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/map.rs:103:9
  21:        0x1008e3b2c - fsrt::scan_directory::h4a7f66d7998cd404
                               at /Users/alexandr/Projects/FSRT/crates/fsrt/src/main.rs:221:34
  22:        0x1008e3b2c - fsrt::main::h01d2ecd2d68dd5c9
                               at /Users/alexandr/Projects/FSRT/crates/fsrt/src/main.rs:241:9
  23:        0x1008bb9b8 - core::ops::function::FnOnce::call_once::h2e201af541a026ec
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  24:        0x1008bb9b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::hef0b091c373b9d2c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  25:        0x1008bb9d8 - std::rt::lang_start::{{closure}}::h23e0725df52f5fbe
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  26:        0x100b2e20c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0c60ab225fafdaa1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  27:        0x100b2e20c - std::panicking::try::do_call::he83c34dec7ecf156
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  28:        0x100b2e20c - std::panicking::try::hf8a127683312d6e6
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  29:        0x100b2e20c - std::panic::catch_unwind::h6bfb2185c735f4ae
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  30:        0x100b2e20c - std::rt::lang_start_internal::{{closure}}::he1235e45f833117a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  31:        0x100b2e20c - std::panicking::try::do_call::h600fcfa83f96c092
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  32:        0x100b2e20c - std::panicking::try::h3ab439188ed13993
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  33:        0x100b2e20c - std::panic::catch_unwind::hb86c613836afcf80
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  34:        0x100b2e20c - std::rt::lang_start_internal::h94fa211da9d06d56
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  35:        0x1008e64e0 - _main
```
 fsrt 0.1.0
cargo 1.65.0 (4bc8f24d3 2022-10-20)
rustc 1.65.0 (897e37553 2022-11-02)

App ID: c3a79af7-56b4-4223-8255-289962173158

**Comment by jwong101** [comment]
Sorry for the late response, we just went through a pretty big rewrite. Can you confirm that it doesn't crash anymore with the most recent version? I just ran fsrt on your app, and it appears that it doesn't crash anymore.

**Comment by jwong101** [comment]
Closing, since the most recent version of FSRT was able to scan this app in prod.
