### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by benjamincjohn** [atlassian-labs/FSRT#8]
We have various issues. Let us know what information you need to better understand the issue.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { error: (Span { lo: BytePos(23273), hi: BytePos(23279), ctxt: #0 }, Unexpected { got: "string", expected: "jsx identifier" }) }', crates/fsrt/src/main.rs:145:18
stack backtrace:
   0:        0x101de4542 - std::backtrace_rs::backtrace::libunwind::trace::h3274e49b4ebf7e53
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x101de4542 - std::backtrace_rs::backtrace::trace_unsynchronized::hd211d632c7624604
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x101de4542 - std::sys_common::backtrace::_print_fmt::h1e774fa26a8ee490
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x101de4542 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2e8cbde22b780fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x101e001aa - core::fmt::write::hd6692086cdd356a7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:        0x101de18ec - std::io::Write::write_fmt::h6043124a2486acbb
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:        0x101de5a1b - std::sys_common::backtrace::_print::h3d78a31fac988d9b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x101de5a1b - std::sys_common::backtrace::print::hdfd67a42b253a0c5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x101de5a1b - std::panicking::default_hook::{{closure}}::h87a12b8b06887dd7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:        0x101de5727 - std::panicking::default_hook::h7f68dad17e0bfaa4
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:        0x101de603f - std::panicking::rust_panic_with_hook::hd57427cbbfc3717a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:        0x101de5f83 - std::panicking::begin_panic_handler::{{closure}}::h33aab6d04e2bba70
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  12:        0x101de49d8 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e7a76f927db9964
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x101de5c4d - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:        0x101e1e4b3 - core::panicking::panic_fmt::hcf6f3c517c6f3cb3
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:        0x101e1e615 - core::result::unwrap_failed::ha988429942445917
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
  16:        0x101b04a09 - core::result::Result<T,E>::unwrap::hc940bdb0a5d8385b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1107:23
  17:        0x101b04a09 - fsrt::ForgeProject::with_files::{{closure}}::{{closure}}::h93435b153ccccbec
                               at /Users/benjamin.john/bitvoodoo-forge/FSRT/crates/fsrt/src/main.rs:135:30
  18:        0x101b04a09 - scoped_tls::ScopedKey<T>::set::ha6406df27315497e
                               at /Users/benjamin.john/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.1/src/lib.rs:137:9
  19:        0x101b0ba39 - better_scoped_tls::ScopedKey<T>::set::h889f33f6c2785c81
                               at /Users/benjamin.john/.cargo/registry/src/github.com-1ecc6299db9ec823/better_scoped_tls-0.1.0/src/lib.rs:55:9
  20:        0x101b0ba39 - fsrt::ForgeProject::with_files::{{closure}}::h00ed4cc8d915cd75
                               at /Users/benjamin.john/bitvoodoo-forge/FSRT/crates/fsrt/src/main.rs:132:13
  21:        0x101b0ba39 - core::iter::traits::iterator::Iterator::fold::h445de6610b337ec9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:2414:21
  22:        0x101b0ba39 - fsrt::ForgeProject::with_files::hcb8d88261ecbfcd5
                               at /Users/benjamin.john/bitvoodoo-forge/FSRT/crates/fsrt/src/main.rs:130:19
  23:        0x101b0ba39 - fsrt::scan_directory::h63c9fa269a9cf3cc
                               at /Users/benjamin.john/bitvoodoo-forge/FSRT/crates/fsrt/src/main.rs:214:20
  24:        0x101b0ba39 - fsrt::main::hde236691b74413de
                               at /Users/benjamin.john/bitvoodoo-forge/FSRT/crates/fsrt/src/main.rs:241:9
  25:        0x101adf2e6 - core::ops::function::FnOnce::call_once::h03a8297a1a309e7f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  26:        0x101adf2e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbae9ece65e495754
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  27:        0x101adf305 - std::rt::lang_start::{{closure}}::hfb122d22700078a1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  28:        0x101dddd0e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb30f3c124d6422bd
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  29:        0x101dddd0e - std::panicking::try::do_call::h6ab65f1fbf11caa5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  30:        0x101dddd0e - std::panicking::try::hb963b3a8541f11db
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  31:        0x101dddd0e - std::panic::catch_unwind::hd044952603e5f56c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  32:        0x101dddd0e - std::rt::lang_start_internal::{{closure}}::h3a2dc7ba533401e5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  33:        0x101dddd0e - std::panicking::try::do_call::h88480942a6edc3bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  34:        0x101dddd0e - std::panicking::try::ha84f131c957dae86
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  35:        0x101dddd0e - std::panic::catch_unwind::hab613c35aec6b94f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  36:        0x101dddd0e - std::rt::lang_start_internal::ha5deaf08dab8765b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  37:        0x101b0f87f - _main
```
fsrt 0.1.0
cargo 1.65.0 (4bc8f24d3 2022-10-20)
rustc 1.65.0 (897e37553 2022-11-02)
App ID: fc9a7108-0027-4cc4-b68d-3e9186008ae2

**Comment by jwong101** [comment]
Closing, since this was fixed in the latest version of FSRT
